import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ViewTransitions } from "next-view-transitions";
import Navbar from "@/components/Navbar";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { redirect } from "next/navigation";
import prisma from "./lib/db";
import { Toaster } from "react-hot-toast";
import BottomBar from "@/components/BottomBar";

const dm_sans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getPermission, getUser} = getKindeServerSession();
  const user = await getUser();

  const requiredPermission = await getPermission("admin:perm");

  const cartCount = user != null ? await prisma.cart.count({where: {kindeAuth: user?.id}}) : -1
  return (
    <html lang="en">
      <ViewTransitions>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            dm_sans.variable
          )}
        >
          <Toaster />
          <Navbar adminPerm={requiredPermission?.isGranted} cartCount={cartCount} />
          <BottomBar adminPerm={requiredPermission?.isGranted} cartCount={cartCount} />
          <div className="max-w-5xl mx-auto">

          {children}
          </div>
          
        </body>
      </ViewTransitions>
    </html>
  );
}
